config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :posts do
  	member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :name, :presence => true,
  				   :length => { :maximum => 50}
  validates :body, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable
	belongs_to :user
	has_many :comments

	validates :title, :presence => true,
					 :length => { :maximum => 50} 
	validates :body, :presence => true

	

	scope :search,  lambda {|query|
		where(["title LIKE ?", "%#{query }%"])
	}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)
		
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id]).destroy

		redirect_to post_path(@post)
	end

	private
	def comment_params
		params.require(:comment).permit(:name, :body)
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.search(params[:search])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end


  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to @post
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to :back
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="comment_content">
		<p><strong><%= comment.name %></strong></p>
		<p><%= comment.body %></p>
		<p><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? && current_user.email == @post.user.email %>
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	<% end %>
</div>

app/views/comments/_form.html.erb
<h3>Add comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
	
		<div class="row">
			<div class="col-md-2"><%= f.label :name %></div>
			<div class="col-md-10"><%= f.text_field :name, :class => "form-control"%></div>
		</div>
		<div class="row">
			<div class="col-md-2"><%= f.label :body %></div>
			<div class="col-md-10"><%= f.text_area :body, :class => "form-control" %></div>
		</div>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-10"><%= f.submit 'Add Comment', :class => 'btn btn-block btn-info' %></div>
		</div>
	
<%end%>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
	
<div class="container">
	<%= render 'posts/navbar' %>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	
	<%= yield %>
		
</div>

<%= render 'posts/footer' %>

</body>
</html>

app/views/posts/_footer.html.erb
<footer>
	<div class="center">
		 follow me 
		<%= link_to image_tag('linkedin.png', :alt => "linkedin"), 'https://www.linkedin.com/profile/view?id=252405573&trk=nav_responsive_tab_profile', :target => "_blank" %> 
		<%= link_to image_tag('github.png', :alt => "github", size: '32x32'), 'https://github.com/SamirArap?tab=repositories', :target => "_blank" %>
		<%= link_to image_tag('twitter.png', :alt => "twitter"), 'http://www.twitter.com', :target => "_blank" %> 
		<%= link_to image_tag('googleplus.png', :alt => "googleplus"), 'http://www.google.com', :target => "_blank" %> 
		<%= link_to image_tag('youtube.png', :alt => "youtube"), 'http://www.youtube.com', :target => "_blank" %> 
		<%= link_to image_tag('mail.png', :alt => "mail") %>  
	</div>
</footer>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">
    	<h2>Houston, we have a problem!</h2>
      <h5><%= pluralize(@post.errors.count, "error") %></h5>
		<p>There were problems with the following fields:</p>
      <ul>
	      <% @post.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
      </ul>
    </div>
<% end %>

	<div class="row">
		<div class="col-md-2"><%= f.label :title %></div>
		<div class="col-md-10"><%= f.text_field :title, :class => "form-control"%></div>
	</div >
	<div class="row">
		<div class="col-md-2"><%= f.label :body %></div>
		<div class="col-md-10"><%= f.text_area :body, :class => "form-control"%></div>
	</div>
		
	

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../posts/index">MY BLOG</a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if !user_signed_in? %>
        <li class="active"><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
      <%else%>  
          <li><%= link_to "New post", new_post_path %></li>
          <li><%= link_to "Logaout", destroy_user_session_path, method: :delete %></li>
      <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/edit.html.erb
<div class="container">
	<h3>Edit post</h3>

	<%= form_for @post do |f| %>
		<%= render(:partial => 'form', :locals => {:f => f})%>
		
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-10"><%= f.submit 'Edit post', :class => 'btn btn-larg btn-block btn-info' %></div>
			</div>
		
	<%end%>
</div>
<br>

app/views/posts/index.html.erb
<div class="stomac">
	<div class="container">

		<h2>My Blog</h2>
		
		<form class="search" role="search">
	      <%= form_tag(@post, :method => 'get') do %>
	       
				<div class="row">
					<div class="col-md-10"><%= text_field_tag('search', params[:search], :class => "form-control") %></div>
		          <div class="col-md-2"><%= submit_tag("Search", :class => 'btn btn-default') %></div>
		        </div
	        
	      <%end%>
	    </form>
		
		<div class="row">
			<div class="col-md-4">I have <%= pluralize(@posts.size, 'post')%></div>
			<div class="col-md-4">
				<% if user_signed_in?%>
					<p>You are login like <strong><%= current_user.email %></strong></p>
				<%end%>
			</div>
			<div class="col-md-4"></div>
		</div>
		
		<hr>
		<div class="post">
			<% @posts.each do |post| %>
				<h2 class="title"><%= link_to post.title, post %></h2>
				<h5><%= truncate(post.body, :length => 80) %></h5>

				<h5>Created by <strong><%= post.user.email %> </strong> and posted at <strong><%= post.created_at.strftime("%B %d. %Y")%></strong> </h5>
				
				<div class="btn-group"> 
			      <%= link_to like_post_path(post), method: :put do %>
			        <%= image_tag("Thumbs_Up.png", :size => '40x40') %>
			        <%= post.get_upvotes.size %>
			      <% end %>
			      <%= link_to dislike_post_path(post), method: :put do %>
			        <%= image_tag("Thumbs_down.png", :size => '40x40') %>
			        <%= post.get_downvotes.size %>
			      <% end %>
			    </div>
			    <hr>
			<%end%>
		</div>	
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h3>Add new post</h3>

	<%= form_for @post do |f| %>
		<%= render(:partial => 'form', :locals => {:f => f})%>
		
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-10"><%= f.submit 'Create new post', :class => 'btn btn-block btn-info' %></div>
			</div>
		
	<%end%>
</div>
<br>

app/views/posts/show.html.erb
<div class="stomac">
	<div class="container">

		<h2>Your post: </h2>

		<div class="btn-group pull-right">
		  <%= link_to like_post_path(@post), method: :put do %>
		    <%= image_tag("Thumbs_Up.png", :size => '40x40') %>
		    <%= @post.get_upvotes.size %>
		  <% end %>
		  <%= link_to dislike_post_path(@post), method: :put do %>
		    <%= image_tag("Thumbs_down.png", :size => '40x40') %>
		    <%= @post.get_downvotes.size %>
		  <% end %>
		</div>

			<div class="row">
				<div class="col-md-2">Title: </div>
				<div class="col-md-8"><strong><%= @post.title %></strong></div>
				<div class="col-md-2"> </div>
			</div>
			<div class="row">
				<div class="col-md-2">Created before: </div>
				<div class="col-md-8"><%= time_ago_in_words(@post.created_at) %></div> 
				<div class="col-md-2"> </div>
			</div>
			<div class="row">
				<div class="col-md-2">Body: </div>
				<div class="col-md-8"><%= @post.body%>  </div>
				<div class="col-md-2"> </div>
			</div>
			<br>
			<div class="row">
				<% if user_signed_in? && current_user.email == @post.user.email %>
					<div class="col-md-2"> </div>
					 <div class="col-md-3"><%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-block btn-info'%> </div> 
					 <div class="col-md-3"><%= link_to "Beck", root_path, :class => 'btn btn-block btn-info'%> </div>  
					 <div class="col-md-3"><%= link_to "Delete", post_path(@post),:class => 'btn btn-block btn-info', method: :delete, data: { confirm: 'Are you sure?'} %> </div>
					 <div class="col-md-1"> </div>
				<%end %>
			</div>


		<h2>Comments</h2>
		<h5><strong><%= @post.comments.count%> Comments </strong></h5>

		<div class="comment">
			<!-- display comments -->
			<%= render @post.comments %>


			<!-- comment form -->
			<%= render 'comments/form'%>
		</div>
	</div>
</div>